server:
  port: 8085
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  resources: 
    static-locations = classpath:/resources/ext/queue/rabbitmq/static/
    