eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring: 
  application:
    #service-ribbon
    name: config-client
  cloud: 
    config: 
      label: master
      profile: dev
      #uri: http://localhost:8888/
      discovery: 
        enabled: true
        serviceId: config-server
    
#hystrix的超时时间
hystrix:
  command:
     default:
       execution:
         timeout:
            enabled: true
         isolation:
            thread:
            # 设置熔断超时时间
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false 