
server: 
  port: 8766
spring: 
  application: 
    name: config-client
    
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  #profiles:
  #  active: native  # 配置使用本地储存
  cloud: 
    config: 
      label: master
      profile: dev
      discovery: 
        enabled: true
        serviceId: config-server
    bus: 
      enabled: true
      trace:
        enabled: true
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
              
management: 
  endpoints: 
    web: 
      exposure: 
        include: bus-refresh
