server:
  port: 8085
  tomcat:
    # 设定URI的解码字符集.
    uri-encoding: UTF-8
    # 设定tomcat的最大工作线程数，默认为: 0
    max-threads: 1000
    max-http-header-size: 8192
    min-spare-threads: 30
#ssl配置
  ssl:
    # 是否支持SSL ciphers.
    #ciphers: 
    # 设定client authentication是wanted 还是 needed.
    #client-auth: 
    # 是否开启ssl，默认: true
    #enabled: 
    # 设定key store中key的别名.
    key-alias: tomcat
    # 访问key store中key的密码.
    #key-password: 
    # 设定持有SSL certificate的key store的路径，通常是一个.jks文件.E:\work\rave\tomcat.keystore
    key-store: classpath:commom/ssl/tomcatkeystore.keystore
    # 设定访问key store的密码.
    key-store-password: 123qwe
    # 设定key store的提供者.
    #key-store-provider: 
    # 设定key store的类型.
    key-store-type: JKS
    # 使用的SSL协议，默认: TLS
    #protocol: 
    # 持有SSL certificates的Trust store.
    #trust-store: 
    # 访问trust store的密码.
    #trust-store-password: 
    # 设定trust store的提供者.
    #trust-store-provider: 
    # 指定trust store的类型.
    #trust-store-type: 
    
spring:
  thymeleaf:
      prefix: classpath:/resources/tomcat/templates/
      suffix: .html